server:
  port: 10000

spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow

logging:
  level:
    ROOT: info
    cn:
      sixlab:
        minesoft:
          singte: debug

st:
  db:
    jdbc: "待替换 127.0.0.1:3306/singte"
    username: "待替换 root"
    pwd: "待替换 123456"
  jwt:
    secret: "待替换 random"
    expire: 3600
