server:
  port: 10000

spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
  data:
    mongodb:
      uri: mongodb://singte:123456@localhost:27017/singte

logging:
  level:
    ROOT: info
    cn:
      sixlab:
        minesoft:
          singte: debug

st:
  jwt:
    secret: "待替换 random"
    expire: 3600
