server:
  port: 10000

spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: html_debug
  data:
    mongodb:
      uri: mongodb://singte:123456@localhost:27017/singte

logging:
  config: classpath:logback-console.xml
  level:
    ROOT: info
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    cn.sixlab.minesoft.singte: debug

st:
  login:
    expire: 60
