server:
  tomcat:
    uri-encoding: UTF-8
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      port-header: X-Forwarded-Port
    threads:
      max: 0
  servlet:
    session:
      timeout: 30s
  forward-headers-strategy: native

spring:
  messages:
    basename: i18n/message
    fallback-to-system-locale: false
  profiles:
    active: local
  application:
    name: singte
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:./st_static,classpath:/static/
  jackson:
    serialization:
      write-dates-as-timestamps: true
  freemarker:
    prefer-file-system-access: false
    content-type: text/html; charset=utf-8
    settings:
      number_format: 0.##
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_include: frame/index.ftlh
      template_exception_handler: rethrow
    template-loader-path: file:./st_templates,classpath:/templates/
  aop:
    auto: true

st:
  initPWD:
