server:
  port: 10000

spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: html_debug
  data:
    mongodb:
      uri: mongodb://singte:123456@localhost:27017/singte

logging:
  config: classpath:logback-console.xml
  level:
    ROOT: info
    cn:
      sixlab:
        minesoft:
          singte: debug

st:
  jwt:
    secret: random
    expire: 3600
